### ISSUE TITLE
(ITS向け)初期設定マニュアルに書くべきこと

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-manual#1]

**Comment by equal-l2** [comment]
ネットワークへの接続方法を書く必要がある
(Wi-Fi?有線?)

**Comment by h-takeyeah** [comment]
配線の取り回しが良いように，使いやすい場所に置きましょう，を書く必要がある．

**Comment by equal-l2** [comment]
現状だとネットワーク内のどこからでもバックエンド・フロントエンドにアクセスできるので、以下のような動きが必要
- 研究室LANがあるならそこに接続する(研究室で何かがあってもそれは研究室側の責任)
- 研究室LANがなくて学内ネットワークに直結しないといけない場合、どこからでもアクセスできてしまう旨を明示的に伝える

(ラズパイにモニタをつけるなら、バックエンド&フロントエンドに外部から接続できない設定にしても良さそう)

**Comment by equal-l2** [comment]
ITSだと認証なしのネットワークに繋いでいるからややこしい設定がなくて済んでいるけど、各研究室には認証なしの口はあるんだろうか？
認証があると誰かのクレデンシャルを使って接続しないといけない。

**Comment by ghost** [comment]
@equal-l2 @h-takeyeah さすがにVPNとか、そちらでのプロキシどうのこうのまで出張してなんやかんやするは感知できないし、ケースバイケース過ぎてマニュアル化しても例外が出ちゃうから、8割はこれでいけます、くらいを目指すべきだと思う。

こればっかりは無理だと思う。
