### ISSUE TITLE
【取説の書き方】自分なりに考えてみました

### ISSUE THREAD

**Issue by ghost** [su-its/ams-manual#10]
@h-takeyeah お前が作るって話だっただろ、って言われたら、もう何も言えないのですが、

夜中の2:30くらいから稼働しております(寝たと言えば寝ましたが、睡眠薬飲んでないので寝れてないです)

そういう愚痴が言いたいわけではないのですが、本日薬を貰いに行かねばならず、ノートPCも持ってない身としては、昼間の作業を委ねたいです。

分からないことが発生したら、遠慮なく聞いてください。今日までなら何とか対応できます。(運転中は死ぬかもしれませんが)

QSGは早めに終わらせなくてはならないと思っており、これを骨子として、皆で分散して、adoc→Tex or pandoc等→word

に持っていきたいです。今週の土日は歯医者と弟のgmailの設定？が終わったら暇なのでそのリソースを割きます。

---

ただし、今週の土日以降は納品してしまうこと、これ以上無茶すると冗談抜きで躁転して何をするか分からない、みたいなヤバい状態が起こりえるし、何なら今躁状態ではない、という証明は出来ないんです。

一応、2級クラスの精神障害者なので、そろそろフェードアウトさせてもらいたいです。

---
## 夜中やったこと

家電の取説をリバースエンジニアリングしてみました。これらをベースに作ってください。

### 普遍的な法則のようなもの

- A4と言う紙のレイアウト上、縦2列くらいじゃないと余白がデカくなる
- A4をフルに使う場合は基本的に図的な説明が多く、かつ全体像を説明する等止むをえない場合使用される
- マーキング(赤線とか)はいらないけど、重要なTipsはそれ自体が印刷したときに背景が別の色になっている。言うまでもなく文字も見やすくなければならない。これについては印刷をしないと分からない。
- 取り扱い説明書とは、よほど豪華でない限り使用されるインクは白黒印刷、あるいはそれに近いものになる。今回は白黒で十分であると思う。
- 色を変える場合、メーカを代表するようなイメージカラーの場合である。例：ダイキン⇒薄い青

---

### 取説(最悪ガバガバで構いません、レビュは絶対しますし、主語が足りない文章が大量に出る事は百も承知です)
- 目次(必須)
  - どんなに糞な取説でも参照性の観点からこれは絶対
- 製品の構成パーツおよび部品名(閲覧者がトラブルシューティングする際に、実機を正しく取り扱うための前提知識を揃えるのが目的)
  - 各製品に関する注意事項は、我々が列挙するより公式HPからパクってこないと「想定の範囲外」が生まれると思う
  - 詳細な画像(特にラズベリーパイ)は自前の画像より公式HPのダウンロードで十分だと思われる。ただし部品の説明は入れましょう。
  - ACアダプタ、SDカード等自明だとしても書いてください、例外なくすべての構成パーツです
  - 全体像はしっかりと明瞭に、モニタも含めて配線も見やすくして **最低** 一枚用意しておいてください
  - どれを使うかはこちら(我が家は私以外ITに疎いです)か、青シャツさんと協議して判断します
- (QSGと重複して構いません)GUIを使った機能の説明
  - 例外なく書いてください
  - 全てのボタンは最低でも列挙して下さい(押下できればそれはボタンです)
- トラブルシューティング
  - 最悪、文字あるいは想定されるパターンを全て列挙してください。
  - パターン分けしてもらえると幸いです。
  - 最悪、こちらでチャートを構えます。(土日潰してやります)(図を作ったり、資料作るのは苦手かもしれないけど好きではあるから...)
- (凄く長くなったら)主要な説明の索引を付けてください。
- (トラブルシューティングに混ぜても良いかもしれません)緊急時のエスカレーション先について⇒基本窓口は遊橋先生に言ってくれ、超緊急の時は、エスカレーション用のITSのGithubのイシューテンプレートに記載してください、いきなり来ないでくださいと書きましょう←私はこの認識なのですが、相違がある場合は可及的速やかに報告してください
- 免責について(何をしたら保証が受けれるか、あるいは受けれなくなるか、そもそもちゃんと使っても一年以上の面倒は見ないは必ず記載)
- (Option)使ったライブラリ、環境、リポジトリのURL

**Comment by equal-l2** [comment]
ご病気が大変なようですので強制的に休んでいただくこととします。
