### ISSUE TITLE
トラブルシューティングマニュアルに書くべきこと

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-manual#2]
まずトラブルを列挙しないと対処の考えようがないので、列挙からやる。

**Comment by h-takeyeah** [comment]
【初期設定のレベル】
Wi-Fiにつながらない

**Comment by ghost** [comment]
これがないと、そもそもマニュアルがただの機能の羅列になってしまうのではないでしょうか

**Comment by h-takeyeah** [comment]
【運用中のトラブル】
- リーダーにカードをタッチしても音が出ない
- フロントエンドの入退室ログのページでエラーコードが表示される
- ダウンロードしたCSVファイルがなんかおかしい

**Comment by ghost** [comment]
@h-takeyeah 全ての要素の粒度がバラバラなのですが、それも含めて私が考えろ、という意味ですか？(それを意図してるなら構いません、私の脳みそが悪いのですから)

この三点以外で起こりうる事は本当にないんですね？

例えば `電源コードは刺さってないか？` の確認もリーダーにタッチして反応しないの中に含めるのですね？

**Comment by h-takeyeah** [comment]
@Stroheim001 思いつくままに挙げたので「この三点以外で起こりうること(トラブル)は本当にないか」と言われると他にもあると思います，と言わざるを得ません．

確かに粒度としてはバラバラですが，まあアイデアなのでよしとしませんか．

**Comment by h-takeyeah** [comment]
危機感なくてすみません

**Comment by ghost** [comment]
@h-takeyeah リーダがいいっていうなら、我々がどうこうすることは出来ません。要するにこのコンテクストにおいて、

貴殿はこの三点を挙げられて、これがブレーンストーミングした結果出たものです、という事で、それ以降は自由だ、なのか、

てめえ(私の事です)が考えろ、音頭とる係(中間管理職)がすることではない(It's none of my business)って言われたらまあ、反論は出来ません。責任も取れませんがｗ

トラシューについては取説の最後らへんにかこうと思ってたのですが、そもそも論なんですけど、あると勘違いしてた私も悪いのですが、クイックスタートガイドに添付されている画像に一切「ハードウェア」の画像がなくて、

電源が正しく刺さっている状態とは？すら提示することが出来ません。

---

もうしわけないのですが、このまま書類qsgを提出した場合、停電、不慮の電源周りのトラブル(間違えて抜いてしまった)等で毎回呼び出されると思います。

それは、貴殿らもそうしたかったはずではないでしょうし、私もそれは一番避けたい事情です(学業に専念して欲しいからです)

必要な画像リストを言わなかった私の過失はあります。

究極的には私が悪いのですが、完成させるために、現在必要な情報をリストアップしている最中です。(家電の取説を見ながら)

**Comment by h-takeyeah** [comment]
@Stroheim001 Discord見れますか？見れたら見てください

**Comment by ghost** [comment]
@h-takeyeah 招待されるかDMされんとみえんで

**Comment by h-takeyeah** [comment]
画像の件に関しては，取説等が完成したらどんな感じになるかをもっと早めに共有しておけば発生しなかった事案ですね．そこはすみませんでした

**Comment by ghost** [comment]
@h-takeyeah デスマーチは慣れたよ、君たちが叩き込んでくれたさ

**Comment by h-takeyeah** [comment]
> トラシューについては取説の最後らへんにかこうと思ってたのですが

というのは私たちの代わりに今書いてるってことですか？自分からは作業してくれと頼んでいないですがどういうことですか？

自分には「@Stroheim001 さんがSlackから抜けて後顧の憂いを断ったが，私らの進捗のなさや無計画さに呆れて作業を再開した」ように見えるのですが……．煽りじゃなくて．

---

もしその気があるなら頼りますが，その気がなかったら以下は無視してください．

- 今トラブル発生時に室に持っていくかどうか，もっていかないとすれば何ができるかを書いたフローチャートを作成しています(ちょっと完成は厳しそうですが)．
- 今，このissueに挙げられた項目に対応するトラブルシュート手順を書いています．
  - いわゆる「こんなときは？」です

これらを踏まえて，ユーザーが自分でトラブルに対処する/諦めて室に持っていくための判断を助ける文書を作るとして，方向性が間違っているんでしょうか？粒度がどうとか言われても正直ピンとこなかったので，もし明確なひな形・テンプレでもあるのなら教えてほしいです．

あと画像はこんな感じのがありますhttps://photos.app.goo.gl/sQ9ZxfrERpWgnKT19

**Comment by h-takeyeah** [comment]
心理的安全性の低いチームですいません(__)

**Comment by ghost** [comment]
@h-takeyeah  デスマになったのは君のマネジメント力云々ではなく遊橋先生の要件定義が甘すぎる事、情報共有に対する認識の著しい欠如が、根本原因だと私は思うのですが、別にITSメンバの誰かを糾弾したくて抜けたとかではありません。

そもそもNuxt,jsについて説明を書く件については4月にもつれ込ませたとしても全うするつもりでいて、故にドキュメントのCIが入っている部分もあります。

(逆を言うと、自分は感知できないし、何が起きてるかも分からない `bou-responder` 等にCIを加えてないのは、逆にTextlint等を入れるとリポジトリが簡素が売りなのに肥大化してしまうからです。)

ただ、取説については、私も現物を購入してまで写真をとるみたいなブルジョワでもなければ、そもそも障害基礎年金(年79万)で生きてる身で、そこから薬代も病院代もケータイ利用料金もガソリン代もねん出しないといけないので、そろえるのが無理だし、それだけのためだけにそんな装置いらないし、という感じでございます。

自分は、はっきり言ってマトモな人間ではありません。どう少なくみても、双極性障害、ADHD、ASD、逆流性食道炎、境界性人格障害、不眠症は発症しているわけです。

参加の動機もそもそも暇だったからでしかないんです。

ただ、自分が強烈なまでのワーカーホリックの素因があること、職業倫理感が強すぎる事、そして何よりASD&ADHDが合体したことによる「 `正論` という `暴言` 」を抑えられない人間だということは知ってて止められないんです。

まあ、正直一番怖いのは青シャツさんがガチギレしてないかなんですけどねｗ

彼が僕にキレても本当に反論の余地はないですからｗ

---

糞長くなりましたが、ちょくちょくコントリビュートしてるのは、先週ほど体調が悪くはない、良いとは言って入ってないけど、って感じなのと、qsgみて、絶対ITSに文句くるわｗｗって確信したからですｗｗ

どういう手段でも構いませんので、どれの画像がどういったニュアンス？あるいは正常であるとか異常であるとか、正しい刺し方、とかの確認事項である、とかの要するにdescriptionが欲しいです。

**Comment by ghost** [comment]
> 心理的安全性の低いチームですいません(__)

チームビルディングって難しいね :kusa:

**Comment by h-takeyeah** [comment]
がんばります
