### ISSUE TITLE
免責事項

### ISSUE THREAD

**Issue by equal-l2** [su-its/ams-manual#3]
- データの消失に対しては責任を負わない（バックアップは必要なら顧客が行う）

**Comment by ghost** [comment]
免責事項は法学的に我々にほとんど瑕疵がないレベルの羅列が必要で、プロダクトの操作ミスを含めて、
全て、我々は免責され、ITSに持ち込まれるときは故障したときだけであって、
君たち(ここで言うのは教授)が仕様変更を要求してITSメンバが応じたとしても、受けられないあるいは仕様変更をちゃんと対応できたとしても、もともとから乖離してるから保証外になること等は最低限書いてないと、俺が死ぬ

**Comment by ghost** [comment]
最も蓋然性のある仕様変更は「システムのタイムカードとしての運用」です。
つまり、特定のユーザのみのデータを抽出し、コアタイムに来ているか、そして、それ以外の時間でどれくらい来ているかを
「見やすく」することを要求されることです。
問題は、これをITSメンバが考えもせず受領してしまい、瑕疵が発生してしまって、青シャツさんと私に作業が降りかかることです。確かに3月は春休みだったり、私はまだ定職についてないので暇ですが、4月以降はそうはいきませんし、まして私は民間企業につくわけではないのでmacを持ち込んで昼休みに仕様変更してsshでpushすることも出来ません。

教授が2時間以内になんとかしろ、とかいうデスマーチ的な横暴に出た時に「それは無理です」と返せるか、そしてそもそも仕様変更する場合はメールないしは、slack等のチャットサービスで応対が可能かの判断をするなどのエスカレーションも記載しなければなりません。

我々にとっては一円も発生してないサービスですが、客にとっては装置代をサンクコストには出来ない、という心理効果はほぼ確実に働くと思ってますし、まあ普通ならそうでしょう、と言う話です

**Comment by ghost** [comment]
@equal-l2 こんな締め切りのキワキワなタイミングで申し訳ございません。

一応、我々には瑕疵は原則ありません、定められた手順通りにやって、なおかつエラーしたときだけ対応します、という形であり、それも原則として遊橋先生を経由して連絡してほしい(換言すると遊橋先生が基本的には窓口だよ)という認識なのですが、相違ないですか？

それと `readme.adoc` に基本的に瑕疵はないんだ、という旨の記載を羅列しているのですが不十分でしたら、教えてください。

これで十分だと判断された場合は、それを取説の方に記載させていただきます。

個人的にはMITライセンスの段階で十分だとは思いますが...念のため....
