### ISSUE TITLE
本リポジトリのライセンス表記の選定

### ISSUE THREAD

**Issue by ghost** [su-its/ams-manual#5]
自分では何が適切か不明なのですが、改竄されて、さも瑕疵が存在するような書き方に変えられた場合は、それは知りません、という事は言うまでもないのですが、そのような意味が含意され運用されるんだけど、読みやすいように変えるような工夫まで規制するほど縛りたいわけではありません。

とりあえず、初期設定時に確認事項が存在し、その説明と何か万が一があった時の確認のリファレンス以上の価値はないのだ、というケースの表記を施したい場合に一番近い著作権表記の選定をして頂けると助かります。

色々投げちゃってすみません。
まあ、言質とってくるか不明ですが、免責したいならなるはやの方が良いかと思います。

**Comment by equal-l2** [comment]
**TL;DR:**
ライセンスを付与しなければ同一性保持権により改変自体が違法です。
オープンソース・ライセンスを使う場合も、たいてい著作者を免責する条項があります。

---

# 著作権(同一性保持権)の発生
まず、この世の全ての著作物は作成された時点で作成者に著作権が発生します。
これは著作者が明示的に宣言したか否かにかかわらず発生します。

この時点で著作者は著作権の一部として同一性保持権(他人に勝手に著作物を改変させない権利)を所持します。
つまり、この時点では誰かが勝手に改変をした場合、その行為自体が違法となります。

# オープンソースと同一性保持権
オープンソースは著作物の改変が根本となる行為ですから、同一性保持権がある状態では各々が著作者に改変を許可してもらう必要があります。
これでは不便なので、あらかじめ著作者が特定の条件下で改変を認める(同一性保持権を弱める)ためにライセンスを付与します。

ただ改変されたもののせいで著作者が責任を取らされても困るので、ふつうオープンソース・ライセンスには著作者を免責する条項があります。
(例えば["Choose a License"](https://choosealicense.com/appendix/)に記載のあるライセンスはごく一部を除いて"Liability"と"Warranty"に●がついていて、「責任や義務を負わない」ことが明文化されています。)

**Comment by equal-l2** [comment]
どのライセンスを選ぶかについて。

# MITライセンス
MITライセンスはドキュメントに使用することもできます。

MITライセンスは、ライセンスの表示を条件に、複製・改変・配布・サブライセンスなどを含む無制限の利用を許可します。
ただし、著作者は著作物・派生物に対して責任を負いません。

参考日本語訳：https://licenses.opensource.jp/MIT/MIT.html

# クリエイティブ・コモンズ - 表示 ("CC BY")
クリエイティブ・コモンズ・ライセンスはその名の通り創造的なコンテンツ(文書、芸術作品など)に対して用いられるライセンスです。

「クリエイティブ・コモンズ - 表示」は、ライセンスの表示を条件に、配布・複製、及び任意目的の改変を許可します。
ただし、著作者は著作物・派生物について責任を負いません。
また、改変者はその改変が著作者によって支持されている旨を主張することはできません。

サブライセンスが許可されないなど、MITライセンスよりはやや厳しいライセンスです。
日本語版：https://creativecommons.org/licenses/by/4.0/legalcode.ja

# CC0
欧米で「パブリック・ドメイン」と呼ばれるものをより明確にしたものです。
一切の著作権を放棄します。つまり、他者に無条件での無制限の利用を認めます。
(国によっては作品の道義的責任などは放棄できないことがあります)

一旦CC0でライセンスしたものは取り消せないことに注意してください。
日本語版：https://creativecommons.org/publicdomain/zero/1.0/legalcode.ja

**Comment by equal-l2** [comment]
まあ"CC BY"が無難かな。

**Comment by ghost** [comment]
@equal-l2 了解です。いすれにせよ、勝手に変更加えて瑕疵を要求することはそもそも出来ないなら正直どれでも良いかなぁ、ということはわかりました。
ただ、ライセンス表記をなしにしてやっちゃう事は問題自体はないでしょうけど、
ウチで派生した書類作りたいとか言われたときに都度連絡されるのもウザいと思うので書いといたほうが無難かなと思った次第です

**Comment by ghost** [comment]
(というか、package.jsonにしれっとISCって書いちゃってるから、違うなら外さないとまずい)
