### ISSUE TITLE
【QSG】指摘、私からの疑問、サジェスチョン等

### ISSUE THREAD

**Issue by ghost** [su-its/ams-manual#9]
@h-takeyeah メンション飛ぶか知りませんが、一応大量の指摘が出たので、PRとは別件でissueとして扱わせて頂きます。

私の日本語も完璧ではないので、そこは違います、と言う部分も多々あると思いますが、そこも含めて一度ご一読頂きまして、作業に取り組んで頂けると幸いです。

---

## 前提
QSGを提出するA4:1枚であると想定します。

これらに添削等を加えた、あるいは分からないので直してほしい所も含めて説明していきます。

---

### 総論

- 全体的に、これが「誰に向けた」書類なのかが分からないです。
- 話の粒度がとてもバラバラ(詳細だったり、大雑把だったり)です。
- 果たして印刷を前提としているとは思えないほど、見づらいです。
- markdownで閲覧される事がさも前提であるかのような記述になっており、HTMLを書いたことがあれば分かると思いますがH3以下はpタグと対して大きさが変わりません(CSSでフォントサイズを弄れば分かるとは思いますが、たぶん標準では分からないと思います、記憶違いだったらごめんなさい)。
- 従って、asciidocのようにtable of contentsがあり、そのリンクに飛べるようになってる(この機能自体はmdにもあったとは思いますが)等の理由で、H4までレベリングして機能を説明している、だったりしたら合理的だとは思いますが、印刷したら私は分かりません。
- tocも当然印刷すれば意味はなくなるので、その事を意識したレイアウトにしてほしいです。
- 私がやってる事なのですが、そもそも印刷しなくてもここまでで話一旦切れますよ、というのを明確にするために `---` を使って強制的に線を引けば、おおよそ分かるとは思います。

---

### 各論

- 学生側利用時の流れに、名前を変更しておきましたが、これ書いてA4:1枚に収まりますか？というか、「入退室ログの記録の一機能です」が自明なうえに、2つしか動作に関する項目がないならいらないと思います。
- もっとひどい話をするとその後に書かれている、warningの内容の方がむしろ重要度が高いと私は認識しています。何故なら学生証を使った入退室ログと謳っている以上前者(2つの動作つまりカードリーダにかざして音が流れる事)は自明ですが、後者はFelicaの仕様で反応している、と言う隠された前提の話だからです。もし、QSGに書くなら、合意する際にFelica機能が反応する事は伝えてないと、不都合が生じる可能性があると思います。
- 補足ですが、この項目を削除した場合、Felicaが反応するぞ、と言う話を取説に書いてください、そして、反応するFelicaの一覧を出せるなら出すべきです。教授あるいは学生はまさかそんなものが認識するあるいは異常動作を引き起こすとまで想定していない可能性があるからです。そして、その仕様は隠された前提で、開発者サイドが情報を独占している以上、情報の非対称性が発生します。
- 金儲けのためならこれは多いに利用できますが、今回はそういう話ではない上に、むしろ情報の非対称性を逆手に取られてクレームつけられたら遊橋先生が困る可能性があります。それだけならまだいいのですが、ひいてはITSが困る、というのが一番私の懸念事項ですので、やめてもらえると助かります。
- 本学、という単語が学生証の前にありますがない時とあるときがあります、統一してください。正直に言うと自明な話なので、なくていいと思うし、このカードリーダに他の大学の学生証をかざしたときに反応をしてしまうのなら、かくべきかもしれませんが、そうでないなら要らないと思います。(他の大学の学生証の下りは、ここに書けない場合、取説に記載してください、これは他の大学の生徒がそもそも入ってくることをあまり想定していないからです。)
- (長くなりますが、一応コロナ対策という建前上、人の往来が多くなる状況を意図的に作るのはマネジメント的に問題なのでは、という設問が我々からすることは不可能ではないと思います。但し、関係は悪化するというのは避けられないでしょうし、印象も悪くはなるでしょう。)
- UIの話でブラウザを使うことは自明な気がします。(C#でapp作りましたを想定されるかもしれませんが)
- 自明とまではいかなくても、A41枚で書かなきゃいけない所に書くべきことなのかな？という疑問です
- 私が浮世離れしてるのかもしれませんが、 `ラズベリーパイ` を `ラズパイ` と表記して全員に伝わるという保証がないならちゃんと書きましょう。
- デフォルトでは三カ月のくだりですが、デフォルトって何の話ですか？最初の画面遷移したときの話ですよね？可変なんですか？人によって解釈にばらつきが出そうな表現は避けましょう。(失礼ながら、貴殿は主語が足りないとつくづく感じるときがあります。一度誰かに見せて、分かってもらえるか確認してもらっても良いかと思います。)
- 現在、研究室に～リアルタイム⇒現在とリアルタイムってこのコンテクスト(換言すると、このシステムでの運用を想定したときの話です)だとダブルミーニングでは？(ダブルミーニングが嫌ならトートロジーに近いものを感じます)
- 全入退室ログ、？？？そんなUIはない(機能はあるけど)なのと 画面下部分では、この研究室で記録されたすべての入退室ログが閲覧できます。(入退室ログの表示、というメニューなのにそれ出来ないのかよ、って話なので、自明につき削除しました)
- ダウンロードするほどでもないが⇒余計なお世話なので削除
- ちょっと⇒削除
- 表示件数は調整は出来ません、選択できるだけです(私の日本語がおかしいのかなぁ？)
- `(デバッグ用)` は内輪の話なので書かないでください。これベータ版ですか、とか言われたらITSが困ります。
- どこにも記載がなかったですが、そもそも設置に行く理由は免責事項の確認、合意を得る事だったと思います。取説から特に重要な箇所を抽出して書いてください。
- ちょっとした話ですが、画面下部分ではなく画面下部、の方が文字数が削れること、 `分` という文字があるかどうかで読み方変わるし、そもそも意味が一緒なんだから基本的には削ってます。残ってたら消しておいて下さい。

---

#### 愚痴

- あんだけシステム名をamsだと拘ってたのに、本システムでは、としか記載がなくて竜頭蛇尾というお気持ちです。
- そのまま採用しろとは言いませんが、略称や固有名詞があるのなら、記載するべきじゃないかなと言う気がしますし、私が書いた `README.adoc` には `ams-system` という事で説明を加えています。認識に齟齬があるなら、早めに正したいので、帰宅後修正しますが、20時以降は、もう絶対に対応できないので、土日マターとさせてください。申し訳ございません。

### 謝辞

最後になりますが、長文失礼します。

**Comment by h-takeyeah** [comment]
圧倒的にいろんなことを理解していなかったということが分かりました．ありがとうございます
